# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            SRojo
tagline:          'A data science journey'
description:      'My journey as a <a href="https://twitter.com/sanrmsanrm" target="_blank">data scientist</a>  with a wide range of interests. Made by <a href="https://twitter.com/sanrmsanrm" target="_blank">@sanrm</a>.'
url:              https://sandrarojo.github.io/
baseurl:          /

author:
  name:           'Sandra Rojo'
  url:            https://twitter.com/sanrmsanrm

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sandrarojo/sandrarojo.github.io
